name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Print current directory and change to testing directory
      run: |
        pwd
        ls
    - name: compile
      run: make
      working-directory: proj2
      
    - name: run java
      run: |
        java gitlet.Main init
        java gitlet.Main log
      working-directory: proj2
      



  

    
