name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Print current directory and change to testing directory
      run: |
        pwd
        ls
    - name: Install dependencies
      run: make
      working-directory: proj2
      
    - name: run java
      run: |
        java gitlet.Main log
        java gitlet.Main init
      working-directory: proj2
      

  # test:
  #   needs: build  # Ensure the build job completes before starting the test job
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3



  

    
