name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: infos
      run: |
        pwd
        ls
    - name: compile
      run: make 
      working-directory: proj2

    - name: check
      run: make check
      working-directory: proj2



  

    
